In [1]:
import pandas as pd

In [3]:
path=r'C:\Users\user\Desktop\30318\mydata.csv'
df=pd.read_csv(path,encoding='cp949')

In [5]:
df.head()

,번호,운영기관명,상품명,운영기관구분,상품구분,학자금유형구분,문의처,대학구분,학년구분,학과구분,...,소득기준,지원금액,특정자격,지역거주여부,신청기간,선발방법,선발인원,자격제한,추천필요여부,제출서류
0,1,목포가톨릭대학교,목포한사랑병원산학협력장학금,대학교,장학금,기타,- 061-280-5103,"4년제(5~6년제포함),특정대학","대학7학기,대학8학기이상",특정학과,...,NaN,- 연간 6000000원 (한 학기당 3000000원)/ 복무조건으로 등록금과는 무관,- 2019. 02월 간호학과 졸업예정자로 성적이 우수하고 품행이 단정한 자 - ...,NaN,- 2018-09-11~2019-01-01,NaN,NaN,NaN,- 지도교수의 추천,- 이력서 - 성적증명서 - 교수추천서
1,2,한국장학재단,인문100년장학금,한국장학재단,장학금,성적우수,- 우수장학부 1599-2290,4년제(5~6년제포함),"대학2학기,대학3학기,대학4학기,대학5학기,대학6학기,대학신입생","교육계열,사회계열,인문계열",...,NaN,"- 등록금 : 장학생 선정 후 매학기별 등록금 전액 지원 (입학금, 수업료, 기성...",* 대한민국 국적소지자로서 국내 4년제 대학의 인문사회계열 학과(부)에 재학중인 ...,NaN,- 2020-05-11 ~ 2020-06-02,- 대학별 배정인원 범위 내에서 선발기준에 따라 대학별 자체 선발,- 1500명 내외 ※ 학교마다 선발하는 인원이 상이하므로 장학부서에 확인 필수,- 인문100년 장학금 장학생 자격 유지자 또는 기존 인문 100년장학생으로 선발...,NaN,"- 신규장학생: 전공탐색유형, 전공확립유형 : 학업계획서, 전인적성장계획서 - ..."
2,3,한국장학재단,우수학생 해외유학장학금,한국장학재단,장학금,성적우수,- 1599-2290,"4년제(5~6년제포함),전문대(2~3년제),해외대학","대학2학기,대학3학기,대학4학기,대학5학기,대학6학기,대학7학기,대학8학기이상,대학신입생","공학계열,교육계열,사회계열,예체능계열,의약계열,인문계열,자연계열,제한없음",...,- 신청일 기준 기초생활수급자 또는 차상위계층인 자,* 유학준비생 (고등학생·국내장학생) - 해외대학 진학을 위한 학업장려비 2학년 월...,"- 대한민국 국적 - 국내 고교 2,3학년 재학(예정)자 중 해외대학 입학을 희망...",NaN,- 2020-03-11 ~ 2020-05-07,"- 서류심사 → 인·적성검사 → 심층면접심사 - 학업실적, 발전가능성, 유학에 대...",- 00명,"- 주민등록상 해외이주 신고자, 영주권자 제외 - 교육부 비인가 고등학교 및 외국...",NaN,- 보호자 개인정보 동의서 - 학교생활기록부 - 자기소개 - 교사의견서 - 기초생...
3,4,국립국제교육원,GKS외국정부초청장학생,관계부처,장학금,기타,02-3668-1353,"4년제(5~6년제포함),일반대학원,해외대학","대학2학기,대학3학기,대학4학기,대학5학기,대학6학기,대학7학기,대학8학기이상,대학...","공학계열,교육계열,사회계열,예체능계열,의약계열,인문계열,자연계열,제한없음",...,NaN,1. 장학금 지원 내역 - 학비 면제 - 항공료 제공 - 생활비 지급 - 보험료 지...,"1. 학사(러시아, 터키, 스리랑카 등)2. 석박사(중국, 러시아, 일본, 독일, ...",NaN,국가별로 상이하므로 홈 페이지 선발 요강 참조,1. 1차 지원-전자문서로 지원2. 1차 합격 후-서류를 갖춰 제출 혹은 직접 공관...,"학사(러시아, 터키 항공대, 스리랑카), 석박사",NaN,NaN,NaN
4,5,국립국제교육원,국비유학생,관계부처,장학금,기타,- 상기선발공고 내용 문의는 메일로 piazza31@korea.kr - 시스템 장...,제한없음,"대학8학기이상,박사과정,석사2학기이상,석사신입생(1학기)","공학계열,교육계열,사회계열,예체능계열,의약계열,인문계열,자연계열,제한없음",...,- 꿈나래 전형의 경우 수급권자·차상위계층·한부모지원대상자,- 국가별 차이있음. 첨부자료 확인. (1년 단위로 장학금 지급),- 한국사능력검정시험 3급(또는 4급) 이상인 사람 - 외국어 시험 성적(첨부파일...,NaN,- 2020-05-21 ~ 2020-06-03,- 1차 서류심사 - 2차 면접시험,- 일반전형 : 40명 - 꿈나래전형 : 20명 - 기술기능인 전형 : 4명,- 원격대학 및 기술대학의 경우 전문학사학위를 받았거나 받을 예정인 사람은 제외 ...,"- 학교의 장의 추천 * 단, 독학자의 경우는 제외",- 응시원서 - 대학졸업증명서 - 병적증명서 - 대학 전 과정 성적증명서 - 주...

In [6]:
df.tail()

,번호,운영기관명,상품명,운영기관구분,상품구분,학자금유형구분,문의처,대학구분,학년구분,학과구분,...,소득기준,지원금액,특정자격,지역거주여부,신청기간,선발방법,선발인원,자격제한,추천필요여부,제출서류
2402,"2,403",문경시장학회,근로장학금,지자체,장학금,지역연고,- 문경시청 총무과 평생교육담당 : 054) 550-6241,NaN,NaN,NaN,...,NaN,"- 1인당 2,000,000원",- 대학 재학생 - 29세 이하 - 문경 소재 중소기업에서 제조/생산직으로 근무하는 자,- 관내 고등학교(문경시에 주소를 두고 상지여자고등학교 졸업한 자 포함)졸업 후 ...,- 2020-04-13 ~ 2020-04-24 18:00,NaN,- 10명,- 등록금 전액 면제 대학교는 제외 - 타장학금의 수혜가 본 장학금의 50%를 초...,- 해당 대학교장(총장 또는 학장),- 장학금 지원신청서 및 추천서 - 개인정보 제공 및 수집 동의서 - 재학증명서 ...
2403,"2,404",한경대학교,공적진출지원장학금,대학교,장학금,기타,NaN,NaN,NaN,NaN,...,NaN,500만원 지급,"※ 재적(재학, 휴학 포함) 중 공직시험 합격자에게 지급-공무원(9급, 7급), 중...",NaN,NaN,NaN,NaN,NaN,NaN,"학생역량강화 장학금 신청서, 공직시험 합격증(사본)"
2404,"2,405",양구군청,저소득주민자녀장학생,지자체,장학금,특기자,- 각 읍 면사무소에서도 문의,NaN,NaN,NaN,...,- 기초생활보장수급자 및 차상위계층 자녀,NaN,- 현저히 타의 모범이 될 만한 선행을 한 자,- 양구군에 부모 혹은 본인이 거주하는자.,- 2018. 12. 05. (수) 18시 까지,NaN,- O명,"- 국가, 지방자치단체, 기타 다른 기관으로부터 장학금 또는 학비보조를 받을 경우...",- 총장 추천,- 장학금신청서 - 서약서 - 동의서 - 재학증명서 - 성적증명서(직전학기) - ...
2405,"2,406",한국장학재단,푸른등대 기부장학금(사무금융우분투재단),한국장학재단,장학금,기타,- 1599-2000,NaN,NaN,NaN,...,- 소득분위가 3구간 이하인 자,"- 학기당 1,500,000원 지원 (생활비 무상보조로 정액 지원)- 1개 학기 (...",- 대한민국 국적의 국내 4년제 및 전문대학교 대학생 - 공고일 현재 잔여 정규학...,NaN,- 2020-01-30 ~ 2020-02-17 18:00까지,- 가계소득 60점 + 성적 40점,- 76명,"- 신입생, 편입생 제외, 졸업학기자",NaN,NaN
2406,"2,407",재단법인 전라북도 인재육성재단,글로벌체험 해외연수 장학생,지자체,장학금,기타,- 063)280 - 2938,"4년제(5~6년제포함),전문대(2~3년제)",NaN,NaN,...,NaN,- 팀장 1000만원 한도 내 지원(연수 계획비용의 80%지원),- 전북도 출신 도내 및 도외 소재 대학 재학생,- 부/모의 주민등록이 도내에 공고일 기준 1년이상 등록된 자,- 2019. 03. 25(월) ~ 04. 02(화),- 1차 서류심사 40점 (연수계획안) - 2차 면접심사 60점 (심층면접),"* 총 35명 (7그룹, 그룹인원 3~5명)",- 장기치료중이거나 건강상 이유 등으로 정상적인 연수활동이 어렵다고 판단되는 자 ...,NaN,- 지도교수(전문가)추천서 - 대학생 그룹과제 해외연수 신청서 (팀원 전원 제출)...

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2407 entries, 0 to 2406
Data columns (total 21 columns):
번호         2407 non-null object
운영기관명      2407 non-null object
상품명        2407 non-null object
운영기관구분     2407 non-null object
상품구분       2407 non-null object
학자금유형구분    2407 non-null object
문의처        2287 non-null object
대학구분       2364 non-null object
학년구분       2328 non-null object
학과구분       2335 non-null object
성적기준       1613 non-null object
소득기준       787 non-null object
지원금액       2223 non-null object
특정자격       2184 non-null object
지역거주여부     1033 non-null object
신청기간       2386 non-null object
선발방법       1052 non-null object
선발인원       1511 non-null object
자격제한       1728 non-null object
추천필요여부     724 non-null object
제출서류       2376 non-null object
dtypes: object(21)
memory usage: 395.0+ KB

In [8]:
df.shape

(2407, 21)

In [9]:
df.isnull()

,번호,운영기관명,상품명,운영기관구분,상품구분,학자금유형구분,문의처,대학구분,학년구분,학과구분,...,소득기준,지원금액,특정자격,지역거주여부,신청기간,선발방법,선발인원,자격제한,추천필요여부,제출서류
0,False,False,False,False,False,False,False,False,False,False,...,True,False,False,True,False,True,True,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,True,False,False,True,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,...,True,False,False,True,False,False,False,True,True,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2402,False,False,False,False,False,False,False,True,True,True,...,True,False,False,False,False,True,False,False,False,False
2403,False,False,False,False,False,False,True,True,True,True,...,True,False,False,True,True,True,True,True,True,False
2404,False,False,False,False,False,False,False,True,True,True,...,False,True,False,False,False,True,False,False,False,False
2405,False,False,False,False,False,False,False,True,True,True,...,False,False,False,True,False,False,False,False,True,True
2406,False,False,False,False,False,False,False,False,True,True,...,True,False,False,False,False,False,False,False,True,False

In [10]:
df.isnull().sum()

번호            0
운영기관명         0
상품명           0
운영기관구분        0
상품구분          0
학자금유형구분       0
문의처         120
대학구분         43
학년구분         79
학과구분         72
성적기준        794
소득기준       1620
지원금액        184
특정자격        223
지역거주여부     1374
신청기간         21
선발방법       1355
선발인원        896
자격제한        679
추천필요여부     1683
제출서류         31
dtype: int64

In [12]:
df['상품명']

0              목포한사랑병원산학협력장학금
1                   인문100년장학금
2                우수학생 해외유학장학금
3                GKS외국정부초청장학생
4                       국비유학생
                ...
2402                    근로장학금
2403                공적진출지원장학금
2404               저소득주민자녀장학생
2405    푸른등대 기부장학금(사무금융우분투재단)
2406           글로벌체험 해외연수 장학생
Name: 상품명, Length: 2407, dtype: object

In [14]:
null_count=df.isnull().sum()
df_null=null_count.reset_index()
df_null.columns=['구분','결측값']
df_null

         구분   결측값
0        번호     0
1     운영기관명     0
2       상품명     0
3    운영기관구분     0
4      상품구분     0
5   학자금유형구분     0
6       문의처   120
7      대학구분    43
8      학년구분    79
9      학과구분    72
10     성적기준   794
11     소득기준  1620
12     지원금액   184
13     특정자격   223
14   지역거주여부  1374
15     신청기간    21
16     선발방법  1355
17     선발인원   896
18     자격제한   679
19   추천필요여부  1683
20     제출서류    31

In [15]:
df_null.sort_values(by='결측값').tail(3)

        구분   결측값
14  지역거주여부  1374
11    소득기준  1620
19  추천필요여부  1683